In [182]:
import numpy as np
import pandas as pd

In [183]:
np.__version__

'1.20.3'

## Question 1

In [184]:
data = pd.read_csv("data.csv")

## Question 2

In [185]:
data.shape

(11914, 16)

there are 11,914 records 

## Question 3

In [186]:
data['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

the answer is Chevrolet, Ford and Volkswagen

## Question 4

In [187]:
audis = data[data.Make == 'Audi']

In [188]:
audis.Model.nunique()

34

the answer is that there are 34 audi models in the dataset

## Question 5

In [197]:
nonulls = data.isnull().sum()

In [200]:
nonulls[nonulls != 0].shape

(5,)

the answer is 5

## Question 6

In [201]:
# 1
median_ec = data['Engine Cylinders'].median()
mec

6.0

In [202]:
# 2
mode_ec = data['Engine Cylinders'].mode()
mode_ec

0    4.0
dtype: float64

In [203]:
# 3
data["Engine Cylinders"].isnull().sum()

30

In [204]:
data["Engine Cylinders"].fillna(4.0, inplace=True)

In [205]:
data["Engine Cylinders"].isnull().sum()

0

In [206]:
data['Engine Cylinders'].median()

6.0

so the median was the same even after filling the missing values with the most frequent value

## Question 7

In [211]:
lotus = data[data.Make == 'Lotus']

In [215]:
lotus

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

In [217]:
lotus = lotus[["Engine HP", "Engine Cylinders"]]
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [220]:
lotus = lotus.drop_duplicates()
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [219]:
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [221]:
X = lotus.values

In [222]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [223]:
XTX = np.dot(X.T, X)

In [224]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [225]:
XTX_inv = np.linalg.inv(XTX)

In [226]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [227]:
temp = np.dot(XTX_inv, X.T)

In [228]:
w = np.dot(temp, y)

In [229]:
w

array([  4.59494481, -63.56432501])

the anser is 4.5949

In [207]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')